//! File-manager menus: "Open with aip…" in Finder, and persona ▸ target menus
//! in Dolphin, Nautilus and Nemo (spec decision 15, plan T58–T59).
//!
//! Every menu item runs the aip binary: `aip pick DIR` for the picker (app
//! builds only) or `aip launch PERSONA TARGET --terminal --dir DIR`. The files
//! are generated, recorded in `state_dir/integrations.json`, regenerated when
//! personas change, and removed by `disable` — only the files aip wrote, and
//! only while they still carry aip's marker.

mod finder;
mod linux;

use crate::{library, paths, terminal};
use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};

/// Every generated file contains this, so `disable` never removes anything
/// aip did not write.
pub const MARKER: &str = "Generated by aip";

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Kind {
    Finder,
    Dolphin,
    Nautilus,
    Nemo,
}

impl Kind {
    pub const ALL: [Kind; 4] = [Kind::Finder, Kind::Dolphin, Kind::Nautilus, Kind::Nemo];

    pub fn name(self) -> &'static str {
        match self {
            Kind::Finder => "finder",
            Kind::Dolphin => "dolphin",
            Kind::Nautilus => "nautilus",
            Kind::Nemo => "nemo",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Kind::Finder => "Finder (macOS)",
            Kind::Dolphin => "Dolphin (KDE)",
            Kind::Nautilus => "Files / Nautilus (GNOME)",
            Kind::Nemo => "Nemo (Cinnamon)",
        }
    }

    pub fn parse(s: &str) -> Option<Kind> {
        Kind::ALL.into_iter().find(|k| k.name() == s)
    }
}

/// The launch targets a menu offers, with their labels.
pub const TARGETS: [(&str, &str); 3] = [
    ("claude", "Claude Code"),
    ("pi", "Pi"),
    ("claude-desktop", "Claude desktop"),
];

static PICKER: AtomicBool = AtomicBool::new(false);

/// Called by the app binary: it has a picker window, so menus get "Choose…".
pub fn set_picker_available() {
    PICKER.store(true, Ordering::Relaxed);
}

fn picker_available() -> bool {
    PICKER.load(Ordering::Relaxed)
}

/// What a menu needs to know to be generated.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MenuContext {
    /// The aip binary the menus run.
    pub exe: PathBuf,
    /// The personas repository (the Nautilus extension reads it live).
    pub root: PathBuf,
    /// Whether `exe` has the picker (`aip pick`).
    pub picker: bool,
    pub home: PathBuf,
}

/// One generated file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct File {
    pub path: PathBuf,
    pub content: String,
    pub executable: bool,
}

#[derive(Debug, Default, Serialize, Deserialize)]
struct Manifest {
    #[serde(default)]
    enabled: BTreeMap<Kind, Installed>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct Installed {
    ctx: MenuContext,
    files: Vec<PathBuf>,
}

fn manifest_path() -> PathBuf {
    paths::state_dir().join("integrations.json")
}

fn load_manifest() -> Manifest {
    fs::read_to_string(manifest_path())
        .ok()
        .and_then(|t| serde_json::from_str(&t).ok())
        .unwrap_or_default()
}

fn save_manifest(m: &Manifest) -> Result<()> {
    let p = manifest_path();
    fs::create_dir_all(p.parent().unwrap())?;
    fs::write(&p, serde_json::to_string_pretty(m)? + "\n")?;
    Ok(())
}

/// The context for menus run by this process's binary.
pub fn current_context(root: &Path) -> Result<MenuContext> {
    let exe = std::env::current_exe().context("finding the aip binary")?;
    let exe = fs::canonicalize(&exe).unwrap_or(exe);
    Ok(MenuContext {
        exe,
        root: root.to_path_buf(),
        picker: picker_available(),
        home: paths::home(),
    })
}

/// The files `kind` needs for these personas.
pub fn files(kind: Kind, ctx: &MenuContext, personas: &[String]) -> Vec<File> {
    match kind {
        Kind::Finder => finder::files(ctx),
        Kind::Dolphin => linux::dolphin(ctx, personas),
        Kind::Nautilus if linux::nautilus_python_present() => linux::nautilus_extension(ctx),
        Kind::Nautilus => linux::nautilus_scripts(ctx, personas),
        Kind::Nemo => linux::nemo(ctx, personas),
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct Status {
    pub name: &'static str,
    pub label: &'static str,
    /// The file manager is on this system.
    pub available: bool,
    pub enabled: bool,
    pub note: String,
}

fn available(kind: Kind) -> bool {
    match kind {
        Kind::Finder => cfg!(target_os = "macos"),
        Kind::Dolphin => cfg!(target_os = "linux") && terminal::on_path("dolphin"),
        Kind::Nautilus => cfg!(target_os = "linux") && terminal::on_path("nautilus"),
        Kind::Nemo => cfg!(target_os = "linux") && terminal::on_path("nemo"),
    }
}

/// Every integration that applies to this OS, with its state.
pub fn status() -> Vec<Status> {
    let m = load_manifest();
    Kind::ALL
        .into_iter()
        .filter(|&k| {
            if cfg!(target_os = "macos") {
                k == Kind::Finder
            } else {
                k != Kind::Finder
            }
        })
        .map(|k| {
            let enabled = m.enabled.contains_key(&k);
            let note = match k {
                Kind::Finder => {
                    "Right-click a folder ▸ Quick Actions (or Services) ▸ Open with aip…".into()
                }
                Kind::Dolphin => "Right-click a folder ▸ aip ▸ persona · target".into(),
                Kind::Nautilus if linux::nautilus_python_present() => {
                    "Right-click a folder ▸ aip (live menu, via nautilus-python)".into()
                }
                Kind::Nautilus => {
                    "Right-click a folder ▸ Scripts ▸ aip (install nautilus-python for a live menu)"
                        .into()
                }
                Kind::Nemo => "Right-click a folder ▸ aip: persona · target".into(),
            };
            Status {
                name: k.name(),
                label: k.label(),
                available: available(k) || enabled,
                enabled,
                note,
            }
        })
        .collect()
}

fn write(f: &File) -> Result<()> {
    if let Some(parent) = f.path.parent() {
        fs::create_dir_all(parent)?;
    }
    if f.path.exists() && !ours(&f.path) {
        bail!(
            "{} already exists and was not made by aip; move it away first",
            f.path.display()
        );
    }
    fs::write(&f.path, &f.content).with_context(|| format!("writing {}", f.path.display()))?;
    #[cfg(unix)]
    if f.executable {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&f.path, fs::Permissions::from_mode(0o755))?;
    }
    Ok(())
}

/// A file or bundle aip generated (it carries the marker).
fn ours(path: &Path) -> bool {
    if path.is_dir() {
        // The Finder Quick Action is a bundle; its document holds the marker.
        return fs::read_to_string(path.join("Contents/document.wflow"))
            .is_ok_and(|t| t.contains(MARKER));
    }
    fs::read_to_string(path).is_ok_and(|t| t.contains(MARKER))
}

fn remove(path: &Path) -> Result<bool> {
    if !path.exists() || !ours(path) {
        return Ok(false);
    }
    if path.is_dir() {
        fs::remove_dir_all(path)?;
    } else {
        fs::remove_file(path)?;
    }
    // Tidy the folders aip made for its own files (Nautilus's scripts/aip).
    if let Some(parent) = path.parent() {
        if parent.file_name().is_some_and(|n| n == "aip") {
            let _ = fs::remove_dir(parent);
        }
    }
    Ok(true)
}

/// Install `kind` (or rewrite it), replacing whatever it installed before.
fn install(m: &mut Manifest, kind: Kind, ctx: MenuContext) -> Result<Vec<PathBuf>> {
    let personas = library::list_personas(&ctx.root)?;
    let new = files(kind, &ctx, &personas);
    let paths: Vec<PathBuf> = new.iter().map(|f| f.path.clone()).collect();
    if let Some(old) = m.enabled.get(&kind) {
        for p in old.files.iter().filter(|p| !paths.contains(p)) {
            remove(p)?;
        }
    }
    if kind == Kind::Finder {
        let bundle = finder::bundle(&ctx);
        if bundle.exists() && !ours(&bundle) {
            bail!(
                "{} exists and was not made by aip; move it away first",
                bundle.display()
            );
        }
    }
    for f in &new {
        write(f)?;
    }
    // Record the bundle, not its inner files, for Finder.
    let recorded = if kind == Kind::Finder {
        vec![finder::bundle(&ctx)]
    } else {
        paths.clone()
    };
    m.enabled.insert(
        kind,
        Installed {
            ctx,
            files: recorded,
        },
    );
    Ok(paths)
}

/// Turn on `kind`; returns a line for the user.
pub fn enable(kind: Kind, root: &Path) -> Result<String> {
    let mut m = load_manifest();
    let ctx = current_context(root)?;
    if kind == Kind::Finder && !ctx.picker {
        bail!("the Finder menu opens the aip app's picker; enable it from the app (or run the app's `aip integrations enable finder`)");
    }
    let written = install(&mut m, kind, ctx)?;
    save_manifest(&m)?;
    after_change(kind);
    Ok(format!(
        "{} menu installed ({} file{})",
        kind.label(),
        written.len(),
        if written.len() == 1 { "" } else { "s" }
    ))
}

/// Turn off `kind`, removing only the files aip installed.
pub fn disable(kind: Kind) -> Result<String> {
    let mut m = load_manifest();
    let Some(inst) = m.enabled.remove(&kind) else {
        return Ok(format!("{} menu was not installed", kind.label()));
    };
    let mut removed = 0;
    for p in &inst.files {
        if remove(p)? {
            removed += 1;
        }
    }
    save_manifest(&m)?;
    after_change(kind);
    Ok(format!(
        "{} menu removed ({removed} file{})",
        kind.label(),
        if removed == 1 { "" } else { "s" }
    ))
}

/// Regenerate every enabled menu (after personas change). Quiet and cheap
/// when nothing is enabled.
pub fn refresh() -> Result<()> {
    let mut m = load_manifest();
    if m.enabled.is_empty() {
        return Ok(());
    }
    let kinds: Vec<(Kind, MenuContext)> =
        m.enabled.iter().map(|(k, i)| (*k, i.ctx.clone())).collect();
    for (k, ctx) in kinds {
        install(&mut m, k, ctx)?;
    }
    save_manifest(&m)
}

/// Remove everything aip installed, for every file manager (uninstall).
pub fn disable_all() -> Result<()> {
    for k in Kind::ALL {
        disable(k)?;
    }
    Ok(())
}

/// Let the file manager notice (best effort).
fn after_change(kind: Kind) {
    if kind == Kind::Finder && cfg!(target_os = "macos") {
        let _ = std::process::Command::new("/System/Library/CoreServices/pbs")
            .arg("-update")
            .status();
    }
}

#[cfg(test)]
mod tests;
