# Generated by aip; `aip integrations disable nautilus` removes it.
# A right-click menu for folders: aip ▸ persona ▸ target. Personas are read
# from the personas folder each time the menu opens.
import os
import subprocess

from gi.repository import GObject, Nautilus

AIP = "/opt/My Apps/aip \"2\"/aip"
PERSONAS = "/home/u/agent-personas/personas"
PICKER = True
TARGETS = [("claude", "Claude Code"), ("pi", "Pi"), ("claude-desktop", "Claude desktop")]


def personas():
    try:
        names = sorted(f[:-5] for f in os.listdir(PERSONAS) if f.endswith(".toml"))
    except OSError:
        names = []
    return [("none", "No persona")] + [(n, n) for n in names]


def run(args):
    subprocess.Popen([AIP] + args, start_new_session=True)


class AipMenu(GObject.GObject, Nautilus.MenuProvider):
    def _menu(self, folder):
        top = Nautilus.MenuItem(name="Aip::top", label="aip")
        sub = Nautilus.Menu()
        top.set_submenu(sub)
        if PICKER:
            choose = Nautilus.MenuItem(name="Aip::choose", label="Choose…")
            choose.connect("activate", lambda *_: run(["pick", folder]))
            sub.append_item(choose)
        for persona, plabel in personas():
            item = Nautilus.MenuItem(name="Aip::p::" + persona, label=plabel)
            inner = Nautilus.Menu()
            item.set_submenu(inner)
            for target, tlabel in TARGETS:
                t = Nautilus.MenuItem(name="Aip::t::%s::%s" % (persona, target), label=tlabel)
                args = ["launch", persona, target]
                if target != "claude-desktop":
                    args.append("--terminal")
                t.connect("activate", lambda _i, a=args: run(a + ["--dir", folder]))
                inner.append_item(t)
            sub.append_item(item)
        return [top]

    def get_file_items(self, *args):
        files = args[-1]
        if len(files) != 1 or not files[0].is_directory() or files[0].get_location() is None:
            return []
        return self._menu(files[0].get_location().get_path())

    def get_background_items(self, *args):
        folder = args[-1].get_location()
        return self._menu(folder.get_path()) if folder is not None else []
