#!/bin/sh
# Generated by aip; `aip integrations disable nautilus` removes it.
# The selected folder, or the folder being shown.
dir=$(printf '%s\n' "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | head -n 1)
[ -n "$dir" ] || dir=$(pwd)
[ -d "$dir" ] || dir=$(dirname "$dir")
exec '/opt/My Apps/aip "2"/aip' launch writer pi --terminal --dir "$dir"
